enabled:
  type: boolean
  default: true
  client: true

enabled_categories:
  type: categories
  default: ""
  client: true
  description: "启用隐藏联系方式开关功能的分类"

resolved_category_id:
  type: category
  default: ""
  client: true
